Homework 1: Introduction to Machine Learning

Q1. Pandas version

In [4]:
import pandas as pd
print(pd.__version__)

3.0.6

Q2. Records count

In [5]:
import os
os.getcwd()

'/workspaces/ml-zoomcamp-homework/01-intro'

In [6]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [15]:
print(f"Number of records in the dataframe: {len(df)}")
print(f"Alternative way to get the number of rows: {df.shape[0]}")

Number of records in the dataframe: 10000
Alternative way to get the number of rows: 10000

In [ ]:
print(f"Number of columns in the dataframe: {len(df.columns)}")
print(f"Alternative way to get the number of columns: {df.shape[1]}")

Nomber of columns in the dataframe: 11
Alternative way to get the number of columns: 11

In [19]:
print(f"Way to get the columns names:")
df.columns

Way to get the columns names:

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [ ]:
print(f"Alternative way to get the columns names:")
list(df.columns)

Alternative way to get the columns names:

['model_year',
 'origin',
 'fuel_type',
 'drivetrain',
 'num_doors',
 'engine_displacement',
 'num_cylinders',
 'horsepower',
 'vehicle_weight',
 'acceleration',
 'fuel_efficiency_mpg']

In [22]:
print(f"Get the columns names + types:")
df.dtypes

Get the columns names + types:

model_year               int64
origin                     str
fuel_type                  str
drivetrain                 str
num_doors                int64
engine_displacement      int64
num_cylinders            int64
horsepower             float64
vehicle_weight           int64
acceleration           float64
fuel_efficiency_mpg    float64
dtype: object

In [24]:
print(f"First few roew to see an example of data:")
df.head()

First few roew to see an example of data:

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q3. Fuel types

In [28]:
print(f"Differents fuel types are presented in the dataset: {df["fuel_type"].nunique()}")
df["fuel_type"].unique()

Differents fuel types are presented in the dataset: 3

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

Q4. Missing values

In [49]:
print(f"How many columns in the dataset have missing values:")
number_of_nulls = df.isnull().sum()
cols_with_nulls = number_of_nulls[number_of_nulls > 0]
cols_with_nulls

How many columns in the dataset have missing values:

horsepower      877
acceleration    264
dtype: int64

In [50]:
print(f"Alternative way to get the number of missing values:")
missing_df = df.isnull().sum()[lambda s: s > 0].to_frame("missing_count")
missing_df

Alternative way to get the number of missing values:

              missing_count
horsepower              877
acceleration            264

In [53]:
print(f"To get the columns names with missing values:")
cols_with_nulls.index

To get the columns names with missing values:

Index(['horsepower', 'acceleration'], dtype='str')

Q5. Max fuel efficiency

In [59]:
print(f"The maximum fuel efficiency of cars from Asia:")
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

The maximum fuel efficiency of cars from Asia:

np.float64(41.2)

Q6. Median value of horsepower

In [88]:
horsepower_median = df["horsepower"].median()
print(f"The median horsepower: {horsepower_median}")

horsepower_frequency = df.groupby("horsepower")["horsepower"].count().sort_values(ascending=False)
#type(horsepower_frequency)   # <class 'pandas.core.series.Series'>
horsepower_most_frequent = horsepower_frequency.head(1)
horsepower_most_frequent_value = horsepower_most_frequent.index[0]
print(f"The most frequent horsepower: {horsepower_most_frequent_value}")

print(f"Built in function to calculate the most frequent horsepower: {df["horsepower"].mode()[0]}")

The median horsepower: 254.0
The most frequent horsepower: 252.0
Built in function to calculate the most frequent horsepower: 252.0

In [92]:
#fill the missing values in the horsepower column with the most frequent value
df_horsepower_modified = df["horsepower"].fillna(horsepower_most_frequent_value)
print(f"New median after removing the missing values: {df_horsepower_modified.median()}")

New median after removing the missing values: 252.0

Q7. Sum of weights

In [112]:
#Select all the cars from Asia
#Select only columns vehicle_weight and model_year
#Select the first 7 values
#Get the underlying NumPy array. Let's call it X.
X = df[df["origin"] == "Asia"][["vehicle_weight","model_year"]].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [ ]:
# Get the transpose of X:
X.T

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [115]:
# Compute matrix-matrix multiplication between the transpose of X and X.
#XTX = X.T @ X
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [117]:
import numpy as np
# Compute the inverse of XTX.
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [118]:
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [ ]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inverse.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [121]:
w.sum()

np.float64(0.36919696904925486)